### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by MainBrainArt** [artineering-io/MNPRX#2]
Hi, in the august Update I'm having a problem with the toolbox and render sequence windows. It throws me an error.
Edit: When I try to update the materials throws me an error.
```

import mnprx_runner

mnprx_runner.openTargetRenderer(MNPR=True)
# Error: openTargetRenderer() got an unexpected keyword argument 'MNPR'
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
# TypeError: openTargetRenderer() got an unexpected keyword argument 'MNPR' # 
import mnprx_runner
mnprx_runner.openMNPRXToolbox(MNPR=True)
# Error: openMNPRXToolbox() got an unexpected keyword argument 'MNPR'
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
# TypeError: openMNPRXToolbox() got an unexpected keyword argument 'MNPR' #

Board_Walk_HI:Floor_SFX has been updated to the latest version
# 1/35 materials updated
Board_Walk_HI:RiceSeedling_SFX has been updated to the latest version
# 2/35 materials updated
Board_Walk_HI:Terrace1_SFX has been updated to the latest version
# 3/35 materials updated
Board_Walk_HI:Water_SFX has been updated to the latest version
# 4/35 materials updated
Board_Walk_HI:lambert5_SFX has been updated to the latest version
# 5/35 materials updated
Board_Walk_HI:terrace2_SFX has been updated to the latest version
# 6/35 materials updated
# Error: 'NoneType' object is not iterable
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "D:\TRABAJOS\Recursos\Lighting_LookDev\MNPRX_RTR_(August 2019)\scripts\mnprx_system.py", line 230, in updateShaderFX
#     mnprx_matPresets.getMaterialAttrs(mat, matAttrs)
#   File "D:\TRABAJOS\Recursos\Lighting_LookDev\MNPRX_RTR_(August 2019)\scripts\mnprx_matPresets.py", line 353, in getMaterialAttrs
#     for attr in setAttrs:
# TypeError: 'NoneType' object is not iterable #  
```

The July update was working without Issues.

I did a clean installation of the plugin.
Everything worked as expected, the materials, lights, config, but the toolbox and target render don't work.

![image](https://user-images.githubusercontent.com/53978126/62824978-f94c5400-bb69-11e9-9644-c2aac4d3c293.png)
![image](https://user-images.githubusercontent.com/53978126/62826666-c95e7a00-bb84-11e9-8431-703729e6dd88.png)

 - Windows 10 SL
 - Maya 2018.6
- Intel I7 6800k
- 32GB Ram
- NVIDIA GTX 1070

Thank You!

**Comment by semontesdeoca** [comment]
Hi @MainBrainArt,

thanks for bringing this to our attention. You have highlighted two problems here:

1. Some tools are not opening from the shelf
2. The material update tool is throwing an error

## 1. Some tools are not opening from the shelf
I just checked the shelf source files in the distribution and everything seems in order.

This problem was most likely caused by having Maya open while updating the MNPRX files (which [shouldn't be](https://artineering.io/projects/MNPRX/docs/update/#replacing-mnprx)). When Maya closes, it automatically saves all shelves. This means that, after updating, the shelf update was most likely overwritten with the old shelf from the open Maya session. Can you help us check if this is the case? 

To check, simply follow these instructions
1. Close all instances of Maya
2. Do the update to the August release of MNPRX (if you already updated, replace the shelf file with a clean one from the distribution). 
3. Start Maya
4. Check if the tools work now

## 2. The material update tool is throwing an error
That is a interesting bug. It seems that you have a material without any attributes, for some reason.
Can you help us check if the following steps solve the error? 

1. Replace the mnprx_matPresets.py file in the MNPRX scripts directory with this one: [matPresets.zip](https://github.com/artineering-io/MNPRX/files/3491346/matPresets.zip)
2. Double click on the `mPre` shelf tool to reload the script file
3. Right click on the `mPre` shelf and try updating the materials again.

---

Please let us know if these two solutions solved your problems =)

**Comment by MainBrainArt** [comment]
Hi @semontesdeoca, Thank you for your quick answer. 

The first problem didn't happen because of having Maya open, but I did find the solution, for some reason if the maya.env has more than 1 blank lines it generates some issues. Because I did a clean installation deleting the July update and installing the august update I had to delete the environment variables lines that were pointing to the July update. 
When I tried to install the August Update it does install but generates those issues, I did it several times (sometimes didn't install, sometimes install but like half of it. Anyways at the moment I cleared my Maya.env blank lines, I installed again and work perfectly.


Now for the second problem the matpreset you handed to me fixes the updating process but all the materials attributes are in -1 value. the path to the textures are empty and even if I put the materials in 1 value doesn't do anything. Maybe it's because of some messy reference, or changes over references in the anim files, I couldn't figure it out.

![image](https://user-images.githubusercontent.com/53978126/62897812-913c7000-bd19-11e9-9bfe-3846212804e6.png)




EDIT: If I reroll to a previous version of the maya file the materials works, I can see it in the viewport and the update works and everything is great but when I load the .ma file again the materials brokes. The screenshot of the materials in Value-1 happens again.


Thank you so much for your answers, hope this helps a little.
And keep the good work with this awesome Render engine, It's really great, I love it.

**Comment by semontesdeoca** [comment]
Alright, thanks for highlighting this to us and finding out why it was not properly working on your side!

Since Maya seems to be so picky, we'll make sure to automatically delete empty lines that the user may have left behind in the Maya.env file upon installation (in the September update). Thanks for bringing this to our attention!

---
The problem with the materials seems incredibly odd to me. You are working on the Run Totti Run shortfilm right? Is there any way you could upload it to Artella so that we can take a look at it? Thanks!

**Comment by MainBrainArt** [comment]
I found a solution, the problem happens if I change the paths texture in the lighting file. The problem is this:

The original foliage file has wrong textures path, those are pointing to a local folder instead of pointing to the environment artella. So, when I open the file I have missing textures, so I fixed it inside the lighting file, and that's what generates the error. 

The scene I'm working on is in the farming/0032/light
These are the steps to replicate the problem:

1. open the 0032_light_update.ma (it will take a while to load because of the missing textures)
2. Fix the path textures to the correct environment path inside the light_update maya file, and save that file.
3. Open the same file and you will see the broken materials on the foliage.


The foliage scene is in props/foliage
To fix it, I had to fix those paths in the original foliage scene, I made a new scene called foliage_fix (I don't have access to modify the original) And I replaced the foliage reference to foliage_fix in the light_update.ma, and everything is solved.


Thanks!!
